title: Luke Foster
description: Ideas about Claude Code, development strategies, and research
baseurl: ""
url: "https://blog.lukefoster.net"
author: Luke Foster

permalink: /posts/:year/:month/:day/:title/

plugins:
  - jekyll-feed

exclude:
  - .gitignore
  - README.md

# Keep static assets in the build output
keep_files:
  - assets
