title: Luke Foster
description: Ideas about Claude Code, development strategies, and research
baseurl: ""
url: "https://lukefoster.net"
author: Luke Foster

permalink: /posts/:year/:month/:day/:title/

plugins:
  - jekyll-feed

exclude:
  - .gitignore
  - README.md
